### ISSUE TITLE
Typo: "Renouveller" instead of "Renouveler"

### ISSUE THREAD

**Issue by Thiht** [ovh/manager#4363]
**Describe the bug**
The word "renouveler" (2 l instead of 1) has a typo in multiple locations:

- here (2 times): https://github.com/ovh/manager/blob/bce8e44218eebeefb5f6dd4999ddce0cd4e47d82/packages/manager/apps/web/client/app/domains/translations/Messages_fr_FR.json#L43
- and here: 
![Capture d’écran 2021-01-29 à 17 20 06](https://user-images.githubusercontent.com/2796344/106300073-4dfbf700-6256-11eb-8d1b-d0845139552d.png)

(and to avoid making a separate issue, there are inconsistencies in the Télécom tab between -ez and -er:  ![Capture d’écran 2021-01-29 à 17 23 22](https://user-images.githubusercontent.com/2796344/106300413-c662b800-6256-11eb-83e3-5f644babaa75.png))

**Comment by antleblanc** [comment]
Thank you @Thiht for reporting us these typos.
We will apply a patch for the next release in order to fix them.

According to your screenshots, you're referring the Website menu which differ
from this repo here which is only about the Control Panel.

We will reach the team in charge of the Website and we will keep you posted once
it will be patched.

Thank you!

**Comment by antleblanc** [comment]
Hi @Thiht!

Regarding the Website Menu, I'm still waiting an update regarding the patch.
We will keep you posted once the patch will be deployed.

Thank you!

**Comment by antleblanc** [comment]
Hi @Thiht !

Just to let you know that the release has been deployed.
Issue is now fixed.

Thank you!
